FROM xario/apollo-scraper:latest
LABEL org.freenas.interactive="false"			\
      org.freenas.version="1.0.0" 			\
      org.freenas.upgradeable="true" 			\
      org.freenas.autostart="false" 			\
      org.freenas.bridged="true" 			\
      org.freenas.volumes="[				\
          {						\
              \"name\": \"/tavels.gob\",			\
              \"descr\": \"Config storage space\"	\
          }				\
      ]"						\
      org.freenas.settings="[ 				\
          {						\
              \"env\": \"SMTP_PASS\",		\
              \"descr\": \"The domain name of the server e.g. example.com\",	\
              \"optional\": false			\
          } 						\
      ]"
